kind: pipeline
type: docker
name: debio indexer
trigger:
  branch:
    - master
  event:
    - pull_request

platform:
  os: linux
  arch: amd64

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: whitelist
    host:
      path: /etc/docker/daemon.json
  - name: toolkit
    host:
      path: /data/drone_data

steps:
  - name: verify pull request
    pull: if-not-exists
    image: alpine/git
    volumes:
      - name: toolkit
        path: /data/drone_data
    commands:
      - /data/drone_data/debio_toolkit -approval -repo=debionetwork/debio-indexer -id=${DRONE_PULL_REQUEST}
    when:
      branch:
        - master

  - name: build - devel
    pull: if-not-exists
    image: docker
    volumes:
      - name: toolkit
        path: /data/drone_data
      - name: whitelist
        path: /etc/docker/daemon.json
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - /data/drone_data/debio_toolkit -vault -env -secret=debio_development/data/indexer
      - docker build -t hub.debio.network/debio_indexer_dev:latest .
      - docker push hub.debio.network/debio_indexer_dev:latest
    when:
      branch:
        - master

  - name: merge pull request
    pull: if-not-exists
    image: alpine/git
    volumes:
      - name: toolkit
        path: /data/drone_data
    commands:
      - /data/drone_data/debio_toolkit -merge -repo=debionetwork/debio-indexer -id=${DRONE_PULL_REQUEST}
    when:
      branch:
        - master

  - name: reload service - devel
    pull: if-not-exists
    image: appleboy/drone-ssh
    volumes:
      - name: toolkit
        path: /data/drone_data
    settings:
      host:
        from_secret: devel_host
      username:
        from_secret: devel_uname
      key_path: /data/drone_data/.ssh/id_rsa
      port: 22
      script:
        - docker stop debio_indexer_dev || true && docker rm debio_indexer_dev || true
        - docker rmi hub.debio.network/debio_indexer_dev:latest
        - docker pull hub.debio.network/debio_indexer_dev:latest
        - docker run -d --network=host --name=debio_indexer_dev --env=DEBIOENV=development -v /etc/localtime:/etc/localtime:ro --restart=always hub.debio.network/debio_indexer_dev:latest
    when:
      branch:
        - master

  - name: notify deployment
    image: appleboy/drone-discord
    pull: if-not-exists
    settings:
      webhook_id:
        from_secret: discord_id
      webhook_token:
        from_secret: discord_token
      message: >
        {{#success build.status}}
        ✅ Build #{{build.number}} of `{{repo.name}}` succeeded.

        📝 Commit by {{commit.author}} on

        `{{commit.branch}}`:

        ```
        {{commit.message}}
        ```

        🌐 {{ build.link }}
        {{else}}
        ❌ Build #{{build.number}} of `{{repo.name}}` failed.

        📝 Commit by {{commit.author}} on

        `{{commit.branch}}`:

        ```
        {{commit.message}}
        ```
        🌐 {{ build.link }}
        🌐 {{ commit.link }}
        {{/success}}
    when:
      status: [ success, failure ]
      branch:
        - master

---
kind: secret
name: devel_host
get:
  path: drone_development/faucet
  name: devel_host
---
kind: secret
name: devel_key
get:
  path: drone_development/faucet
  name: devel_key
---
kind: secret
name: devel_uname
get:
  path: drone_development/faucet
  name: devel_uname
---
kind: secret
name: discord_id
get:
  path: drone_common_config/webhook
  name: discord_id
---
kind: secret
name: discord_token
get:
  path: drone_common_config/webhook
  name: discord_token