apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "debio-indexer.fullname" . }}
  labels:
    {{- include "debio-indexer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "debio-indexer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "debio-indexer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "debio-indexer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if and .Values.config.elasticSearch.node .Values.config.elasticSearch.password .Values.config.elasticSearch.username }}
            - name: ELASTICSEARCH_NODE
              valueFrom:
                secretKeyRef:
                  name: {{ include "debio-indexer.elasticSearchSecretName" . }}
                  key: node
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "debio-indexer.elasticSearchSecretName" . }}
                  key: password
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "debio-indexer.elasticSearchSecretName" . }}
                  key: username
            {{- end }}
            {{- if .Values.config.minimalStartingBlock }}
            - name: MINIMAL_STARTING_BLOCK
              valueFrom:
                secretKeyRef:
                  name: {{ include "debio-indexer.minimalStartingBlockSecretName" . }}
                  key: minimalStartingBlock
            {{- end }}
            {{- if .Values.config.requestServiceContractAddress }}
            - name: REQUEST_SERVICE_CONTRACT_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: {{ include "debio-indexer.requestServiceContractAddressSecretName" . }}
                  key: requestServiceContractAddress
            {{- end }}
            {{- if .Values.config.substrateUrl }}
            - name: SUBSTRATE_URL
              value: {{ .Values.config.substrateUrl }}
            {{- end }}
            {{- if .Values.config.web3Rpc }}
            - name: WEB3_RPC
              valueFrom:
                secretKeyRef:
                  name: {{ include "debio-indexer.web3RpcSecretName" . }}
                  key: web3Rpc
            {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          {{- if .Values.config.startupProbe.path }}
          startupProbe:
            httpGet:
              path: {{ .Values.config.startupProbe.path }}
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
            successThreshold: 1
          {{- end }}
          {{- if .Values.config.livenessProbe.path }}
          livenessProbe:
            httpGet:
              path: {{ .Values.config.livenessProbe.path }}
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          {{- end }}
          {{- if .Values.config.readinessProbe.path }}
          readinessProbe:
            httpGet:
              path: {{ .Values.config.readinessProbe.path }}
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          {{- end }}
