{{- if and .Values.config.elasticSearch.node .Values.config.elasticSearch.password .Values.config.elasticSearch.username }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-indexer.elasticSearchSecretName" . }}
type: Opaque
data:
  node: {{ .Values.config.elasticSearch.node | b64enc }}
  password: {{ .Values.config.elasticSearch.password | b64enc }}
  username: {{ .Values.config.elasticSearch.username | b64enc }}

---
{{- end }}
{{- if .Values.config.minimalStartingBlock }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-indexer.minimalStartingBlockSecretName" . }}
type: Opaque
data:
  minimalStartingBlock: {{ .Values.config.minimalStartingBlock | b64enc }}

---
{{- end }}
{{- if .Values.config.requestServiceContractAddress }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-indexer.requestServiceContractAddressSecretName" . }}
type: Opaque
data:
  requestServiceContractAddress: {{ .Values.config.requestServiceContractAddress | b64enc }}

---
{{- end }}
{{- if .Values.config.web3Rpc }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-indexer.web3RpcSecretName" . }}
type: Opaque
data:
  web3Rpc: {{ .Values.config.web3Rpc | b64enc }}

{{- end }}
