name: Deployer

on:
  push:
    branches:
      - main
      - releases/**
  release:
    types:
      - published

concurrency:
  group: deployer

jobs:
  build-and-push-docker-image:
    name: Build and Push Docker Image
    uses: ./.github/workflows/builder.yaml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy-to-testnet:
    needs: build-and-push-docker-image
    if: ${{ github.event_name != 'release' }}
    runs-on: ubuntu-20.04
    environment:
      name: testnet
    permissions:
      id-token: write
      contents: read
    name: Deploy to Testnet
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.TESTNET_GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.TESTNET_GOOGLE_WORKLOAD_IDENTITY_SERVICE_ACCOUNT }}
      - name: Get GKE Credentials
        id: get-gke-credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ secrets.TESTNET_GKE_CLUSTER_NAME }}
          location: ${{ secrets.TESTNET_GKE_LOCATION }}
          use_internal_ip: true
          use_auth_provider: true
      - name: Tunneling SSH connections
        id: ssh-compute
        uses: google-github-actions/ssh-compute@v0
        with:
          instance_name: ${{ secrets.TESTNET_BASTION_INSTANCE_NAME }}
          zone: ${{ secrets.TESTNET_BASTION_INSTANCE_ZONE }}
          ssh_private_key: ${{ secrets.TESTNET_BASTION_SSH_PRIVATE_KEY }}
          flags: --ssh-flag="-L 8888:127.0.0.1:8888"
          command: 'echo Tunneling SSH connections'
      - name: Setup Helm
        id: setup-helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.9.4'
      - name: Perform Deployment
        run: |
          helm repo add debionetwork https://charts.debio.network
          helm repo update
          HTTPS_PROXY=127.0.0.1:8888 helm upgrade ${{ github.event.repository.name }} debionetwork/debio-app-deployer \
            --install \
            --set-string nameOverride=${{ github.event.repository.name }} \
            --set-string image.repository=${{ github.event.repository.full_name }} \
            --set-string image.tag=${{ github.event.release.tag_name }} \
            --set containerPort=3000 \
            --set-string serviceAccount.name=${{ github.event.repository.name }} \
            --set-string serviceAccount.annotations."iam\.gke\.io/gcp-service-account"=${{ github.event.repository.name }}@${{ secrets.TESTNET_GCP_PROJECT_ID }}.iam.gserviceaccount.com \
            --set config.secretsStore.enabled=true \
            --set-string config.secretsStore.providerClass=${{ github.event.repository.name }}-secrets-store-provider \
            --set-string config.secretsStore.name=${{ github.event.repository.name }}-secrets-store \
            --set service.port=3000 \
            --set-string resources.requests.cpu=100m \
            --set-string resources.requests.memory=512Mi \
            --set-string resources.limits.cpu=300m \
            --set-string resources.limits.memory=1024Mi \
            --set replicaCount=1 \
            --set autoscaling.enabled=true \
            --set autoscaling.minReplicas=1 \
            --set autoscaling.maxReplicas=1 \
            --set-string nodeSelector.node_pool=general \
            --set-string nodeSelector."iam\.gke\.io/gke-metadata-server-enabled"="true"
          HTTPS_PROXY=127.0.0.1:8888  kubectl rollout status deployment/${{ github.event.repository.name }}

  deploy-to-mainnet:
    needs: build-and-push-docker-image
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-20.04
    environment:
      name: mainnet
    permissions:
      id-token: write
      contents: read
    name: Deploy to Mainnet
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.MAINNET_GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.MAINNET_GOOGLE_WORKLOAD_IDENTITY_SERVICE_ACCOUNT }}
      - name: Get GKE Credentials
        id: get-gke-credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ secrets.MAINNET_GKE_CLUSTER_NAME }}
          location: ${{ secrets.MAINNET_GKE_LOCATION }}
          use_internal_ip: true
          use_auth_provider: true
      - name: Tunneling SSH connections
        id: ssh-compute
        uses: google-github-actions/ssh-compute@v0
        with:
          instance_name: ${{ secrets.MAINNET_BASTION_INSTANCE_NAME }}
          zone: ${{ secrets.MAINNET_BASTION_INSTANCE_ZONE }}
          ssh_args: '-4 -L8888:127.0.0.1:8888 -N -q -f'
          ssh_private_key: ${{ secrets.MAINNET_BASTION_SSH_PRIVATE_KEY }}
      - name: Setup Helm
        id: setup-helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.9.4'
      - name: Perform Deployment
        run: |
          helm repo add debionetwork https://charts.debio.network
          helm repo update
          HTTPS_PROXY=127.0.0.1:8888 helm upgrade ${{ github.event.repository.name }} debionetwork/debio-app-deployer \
            --install \
            --set-string nameOverride=${{ github.event.repository.name }} \
            --set-string image.repository=${{ github.event.repository.full_name }} \
            --set-string image.tag=${{ github.event.release.tag_name }} \
            --set containerPort=3000 \
            --set-string serviceAccount.name=${{ github.event.repository.name }} \
            --set-string serviceAccount.annotations."iam\.gke\.io/gcp-service-account"=${{ github.event.repository.name }}@${{ secrets.MAINNET_GCP_PROJECT_ID }}.iam.gserviceaccount.com \
            --set config.secretsStore.enabled=true \
            --set-string config.secretsStore.providerClass=${{ github.event.repository.name }}-secrets-store-provider \
            --set-string config.secretsStore.name=${{ github.event.repository.name }}-secrets-store \
            --set service.port=3000 \
            --set-string resources.requests.cpu=100m \
            --set-string resources.requests.memory=512Mi \
            --set-string resources.limits.cpu=300m \
            --set-string resources.limits.memory=1024Mi \
            --set replicaCount=1 \
            --set autoscaling.enabled=true \
            --set autoscaling.minReplicas=1 \
            --set autoscaling.maxReplicas=1 \
            --set-string nodeSelector.node_pool=general \
            --set-string nodeSelector."iam\.gke\.io/gke-metadata-server-enabled"="true"
          HTTPS_PROXY=127.0.0.1:8888  kubectl rollout status deployment/${{ github.event.repository.name }}
